" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'flazz/vim-colorschemes.git'
Plugin 'vladbalmos/vim-test.git'
Plugin 'evidens/vim-twig.git'
Plugin 'scrooloose/nerdtree'
Plugin 'jiangmiao/auto-pairs.git'
Plugin 'tmhedberg/matchit'
Plugin 'tpope/vim-surround.git'
Plugin 'rking/ag.vim.git'
Plugin 'benmills/vimux.git'
Plugin 'majutsushi/tagbar.git'
Plugin 'mattn/emmet-vim.git'
Plugin 'tpope/vim-pathogen.git'
Plugin 'tpope/vim-fugitive.git'
Plugin 'xolox/vim-misc.git'
Plugin 'tpope/vim-unimpaired.git'
Plugin 'moll/vim-node.git'
Plugin 'benekastah/neomake.git'
Plugin 'ctrlpvim/ctrlp.vim.git'
Plugin 'xolox/vim-colorscheme-switcher.git'
Plugin 'ervandew/supertab'

if !filereadable($HOME . '/.vim/disable-ycm-plugin.flag')
    Plugin 'Valloric/YouCompleteMe'
endif

Plugin 'joonty/vdebug.git'
Plugin 'jelera/vim-javascript-syntax.git'
Plugin 'stephpy/vim-yaml.git'
Plugin 'scrooloose/nerdcommenter.git'
Plugin 'Shutnik/jshint2.vim.git'
Plugin 'chriskempson/base16-vim'
